approvals:
  # check will fail if there is no approval
  minimum: 1
  groups:
    - name: 'PyTorch Lightning'
      minimum: 0
      from:
        - awaelchli
        - Borda
        - carmocca
        - ethanwharris
        - kaushikb11
        - krshrimali
        - otaj
        - rohitgr7
        - tchaton
        - williamFalcon
    - name: 'Lightning Apps'
      minimum: 0
        - alecmerdler
        - awaelchli
        - hhsecond
        - lantiga
        - manskx
        - nohalon
        - tchaton
